services:
  logz-metrics-handler:
    build:
      context: .
    image: logz-metrics-handler
    container_name: logz-metrics-handler
    stdin_open: true
    tty: true
    environment:
      EU_API_TOKEN: "${EU_API_TOKEN}"       # Set in .env file
      NA_API_TOKEN: "${NA_API_TOKEN}"       # Set in .env file
      CONFLUENCE_PASSWORD: "${CONFLUENCE_PASSWORD}"  # Set in .env file
    volumes:
      - "./customers.yaml:/app/customers.yaml"
    command: [
        "--platform", "prd",
        "--date", "2025-01-30",
        "--start_time", "08:00:00Z",
        "--end_time", "10:00:00Z",
        "--time_range", "7",
        "--eu_token", "${EU_API_TOKEN}",
        "--na_token", "${NA_API_TOKEN}",
        "--customers_file", "/app/customers.yaml",
        "--csv_filename", "output.csv",
        "--confluence_url", "http://192.168.0.107:8090/",
        "--confluence_username", "logzio-reporter",
        "--confluence_password", "${CONFLUENCE_PASSWORD}",
        "--space_key", "SE",
        "--page_title", "Logz.io Metrics Report"
    ]